name: Build and deploy .NET Core application to Web App RSWebAppContentBlogApp20241118104730
on:
  push:
    branches:
    - main
env:
  AZURE_WEBAPP_NAME: RSWebAppContentBlogApp20241118104730
  AZURE_WEBAPP_PACKAGE_PATH: src/RS.WebApp.ContentBlog.App/published
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 9.0.x
  WORKING_DIRECTORY: src/RS.WebApp.ContentBlog.App
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
